### ISSUE TITLE
NPE on setLicense

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#216]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void net.opendasharchive.openarchive.db.Project.setLicenseUrl(java.lang.String)' on a null object reference
	at net.opendasharchive.openarchive.projects.EditProjectActivity.updateLicense(EditProjectActivity.java:198)
	at net.opendasharchive.openarchive.projects.EditProjectActivity.onPause(EditProjectActivity.java:64)
	at android.app.Activity.performPause(Activity.java:8001)

**Comment by n8fr8** [comment]
net.opendasharchive.openarchive.db.Project.getLicenseUrl()' on a null object reference
	at net.opendasharchive.openarchive.publish.PublishService.doPublish(PublishService.java:161)
	at net.opendasharchive.openarchive.publish.PublishService.run(PublishService.java:124)
	at java.lang.Thread.run(Thread.java:764)

**Comment by n8fr8** [comment]
It seems like this was caused by media still trying to upload after a project was deleted.
