### ISSUE TITLE
Crash when trying to add new Dropbox space

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#261]
**Describe the bug**
When adding a new space of type Dropbox, the app crashes immediately

**To Reproduce**
1. Tap on upper left hand corner icon
2. type on upper right hand + icon
3. choose "Dropbox" as space type
4. CRASH!

**Expected behavior**
flow for authenticating Dropbox is shown

**Environment (please complete the following information):**
 - OS version: Android 10
 - Device: Pixel 4A
 - App Version: latest in DEV

**Additional context**
Crash log

    
    --------- beginning of crash
2021-09-24 13:29:01.847 20779-20779/net.opendasharchive.openarchive.release E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.opendasharchive.openarchive.release, PID: 20779
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.opendasharchive.openarchive.release/net.opendasharchive.openarchive.services.dropbox.DropboxLoginActivity}: java.lang.IllegalStateException: URI scheme in your app's manifest is not set up correctly. You should have a com.dropbox.core.android.AuthActivity with the scheme: db-foo
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: URI scheme in your app's manifest is not set up correctly. You should have a com.dropbox.core.android.AuthActivity with the scheme: db-foo
        at com.dropbox.core.android.AuthActivity.checkAppBeforeAuth(AuthActivity.java:287)
        at com.dropbox.core.android.Auth.startOAuth2Authentication(Auth.java:67)
        at com.dropbox.core.android.Auth.startOAuth2Authentication(Auth.java:27)
        at com.dropbox.core.android.Auth.startOAuth2Authentication(Auth.java:19)
        at net.opendasharchive.openarchive.services.dropbox.DropboxLoginActivity.attemptLogin(DropboxLoginActivity.kt:124)
        at net.opendasharchive.openarchive.services.dropbox.DropboxLoginActivity.onCreate(DropboxLoginActivity.kt:58)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-09-24 13:29:01.847 20779-20779/net.opendasharchive.openarchive.release E/ACRA: ACRA caught a RuntimeException for net.opendasharchive.openarchive.release
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.opendasharchive.openarchive.release/net.opendasharchive.openarchive.services.dropbox.DropboxLoginActivity}: java.lang.IllegalStateException: URI scheme in your app's manifest is not set up correctly. You should have a com.dropbox.core.android.AuthActivity with the scheme: db-foo
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: URI scheme in your app's manifest is not set up correctly. You should have a com.dropbox.core.android.AuthActivity with the scheme: db-foo
        at com.dropbox.core.android.AuthActivity.checkAppBeforeAuth(AuthActivity.java:287)
        at com.dropbox.core.android.Auth.startOAuth2Authentication(Auth.java:67)
        at com.dropbox.core.android.Auth.startOAuth2Authentication(Auth.java:27)
        at com.dropbox.core.android.Auth.startOAuth2Authentication(Auth.java:19)
        at net.opendasharchive.openarchive.services.dropbox.DropboxLoginActivity.attemptLogin(DropboxLoginActivity.kt:124)
        at net.opendasharchive.openarchive.services.dropbox.DropboxLoginActivity.onCreate(DropboxLoginActivity.kt:58)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by ozgegn** [comment]
Hi,
PR is created;
https://github.com/OpenArchive/Save-app-android/pull/262

**Comment by n8fr8** [comment]
I do have a "dropbox_key" value in my BuildConfig already. The app would not have compiled without it being there. The error that is being display seems to be something different:

2021-10-25 15:27:47.367 26627-26627/net.opendasharchive.openarchive.release E/ACRA: ACRA caught a RuntimeException for net.opendasharchive.openarchive.release
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.opendasharchive.openarchive.release/net.opendasharchive.openarchive.services.dropbox.DropboxLoginActivity}: java.lang.IllegalStateException: URI scheme in your app's manifest is not set up correctly. You should have a com.dropbox.core.android.AuthActivity with the scheme: db-foo
