### ISSUE TITLE
Crashes when changing settings

### ISSUE THREAD

**Issue by uniqx** [OpenArchive/Save-app-android#448]
**Describe the bug**

crash:

```
2023-06-06 11:55:17.349  4702-4702  AndroidRuntime          net...sharchive.openarchive.release  E  FATAL EXCEPTION: main
                                                                                                    Process: net.opendasharchive.openarchive.release, PID: 4702
                                                                                                    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                                                                    	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
                                                                                                    	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
                                                                                                    	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
                                                                                                    	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
                                                                                                    	at com.google.android.gms.common.SupportErrorDialogFragment.show(com.google.android.gms:play-services-base@@18.2.0:1)
                                                                                                    	at com.google.android.gms.common.GoogleApiAvailability.zad(com.google.android.gms:play-services-base@@18.2.0:8)
                                                                                                    	at com.google.android.gms.common.GoogleApiAvailability.showErrorDialogFragment(com.google.android.gms:play-services-base@@18.2.0:5)
                                                                                                    	at net.opendasharchive.openarchive.MainActivity.onProviderInstallFailed(MainActivity.kt:536)
                                                                                                    	at com.google.android.gms.security.zza.onPostExecute(com.google.android.gms:play-services-basement@@18.2.0:6)
                                                                                                    	at android.os.AsyncTask.finish(AsyncTask.java:771)
                                                                                                    	at android.os.AsyncTask.access$900(AsyncTask.java:199)
                                                                                                    	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**To Reproduce**
1. Start app in emulator (API level 31, no GAAPS)
2. to settings
4. change a couple of settings
5. observe random crashes

**Expected behavior**
No crash

**Comment by tladesignz** [comment]
@uniqx, can you reproduce that with the latest beta builds?
