### ISSUE TITLE
image upload crash

### ISSUE THREAD

**Issue by uniqx** [OpenArchive/Save-app-android#450]
**Describe the bug**

```
2023-06-13 23:56:14.829 26480-26480 AndroidRuntime          net...sharchive.openarchive.release  E  FATAL EXCEPTION: main
                                                                                                    Process: net.opendasharchive.openarchive.release, PID: 26480
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Long net.opendasharchive.openarchive.db.Collection.getId()' on a null object reference
                                                                                                    	at net.opendasharchive.openarchive.MainActivity.importMedia(MainActivity.kt:388)
                                                                                                    	at net.opendasharchive.openarchive.MainActivity.importMedia(MainActivity.kt:350)
                                                                                                    	at net.opendasharchive.openarchive.MainActivity.access$importMedia(MainActivity.kt:65)
                                                                                                    	at net.opendasharchive.openarchive.MainActivity$onCreate$1$3.invoke(MainActivity.kt:141)
                                                                                                    	at net.opendasharchive.openarchive.MainActivity$onCreate$1$3.invoke(MainActivity.kt:136)
                                                                                                    	at net.opendasharchive.openarchive.util.extensions.CoroutineExtensionKt$executeAsyncTaskWithList$1$result$1.invokeSuspend(CoroutineExtension.kt:27)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@185d5da, Dispatchers.Main.immediate]
```
crash happens on this line: [/app/src/main/java/net/opendasharchive/openarchive/MainActivity.kt#L488](https://github.com/OpenArchive/Save-app-android/blob/8f59d34/app/src/main/java/net/opendasharchive/openarchive/MainActivity.kt#L488)

**To Reproduce**
1. setup Save to use nextcloud
2. create a folder
3. upload a image (in my tests I've used an Image crated with the emulators camera app)
4. crash

Encountered this in the Emulator on both API level 31 (without GAPPS) and 33 (with GAPPS)

**Expected behavior**

Upload file, no crash

**Comment by uniqx** [comment]
just re-based on latest master, the issue seems gone :tada:
