### ISSUE TITLE
Crash when attemting to re-upload previously failed upload

### ISSUE THREAD

**Issue by uniqx** [OpenArchive/Save-app-android#502]
**Describe the bug**
I found an app crash.

**To Reproduce**
1. You'll need to prepare a failed upload (to dropbox, not sure if it's the same for other storage spaces)
2. long-press the failed upload
3. click upload
4. observe crash

**Expected behavior**
I expected that the app should start uploading or display an error message (instead of crashing)

**Screenshots**
[device-2023-09-25-141516.webm](https://github.com/OpenArchive/Save-app-android/assets/674081/4529083d-ffde-411b-83a5-594c8a11b74a)

**Environment (please complete the following information):**
 - OS version: Android Emulator SDK 30 (with GAPPS, Android 11) 
 - Device: [e.g. Samsung Galaxy A2]
 - App Version current master branch (between 0.3.0-alpha7 and 0.3.0-alpha8)

**Additional context**

I've also captured the exception:

```
FATAL EXCEPTION: main
  Process: net.opendasharchive.openarchive.release, PID: 1660
  android.database.sqlite.SQLiteException: near "AND": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM MEDIA WHERE AND selected = 1
  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
  at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
  at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
  at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1545)
  at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1392)
  at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1263)
  at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1469)
  at com.orm.SugarRecord.find(SugarRecord.java:201)
  at com.orm.SugarRecord.find(SugarRecord.java:187)
  at net.opendasharchive.openarchive.db.Media$Companion.getSelected(Media.kt:88)
  at net.opendasharchive.openarchive.db.MediaAdapter$mActionModeCallback$1.onActionItemClicked(MediaAdapter.kt:179)
  at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2658)
  at androidx.appcompat.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:172)
  at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImpl.java:3022)
  at androidx.appcompat.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
  at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
  at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
  at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
  at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
  at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
  at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
  at android.view.View.performClick(View.java:7448)
  at android.view.View.performClickInternal(View.java:7425)
  at android.view.View.access$3600(View.java:810)
  at android.view.View$PerformClick.run(View.java:28305)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:223)
  at android.app.ActivityThread.main(ActivityThread.java:7656)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Here's the code snippet where the crash happens (Media.kt:88):

```
        fun getSelected(): List<Media> {
            return find(Media::class.java, "AND selected = 1")
        }
```

**Comment by foundscapes** [comment]
This also just happened to me, will wait until you updated the upload process to the new designs to re-test

Environment (please complete the following information):

    OS version: Android 12
    Device: Google Pixel 3a
    App Version: 0.3.0-beta1

**Comment by foundscapes** [comment]
@purvi-ranawat can you please test this now thanks!

**Comment by purvi-ranawat** [comment]
@foundscapes / @tladesignz : This is working fine now.

No Crash happened when we attempt to re-upload previously failed upload

Environment : 
OS : Android 11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build : 0.3.0-beta6

**Comment by foundscapes** [comment]
great, thanks @purvi-ranawat
