### ISSUE TITLE
Crash on Nearby Receive when toggling 'paired devices only'

### ISSUE THREAD

**Issue by rocodes** [OpenArchive/Save-app-android#52]
Toggling 'Paired devices only?'  in NearbyActivity results in a crash (although when the app is re-opened, the setting is still updated).

`                                                                                --------- beginning of crash
12-15 14:52:37.171 15123-15285/net.opendasharchive.openarchive.release E/AndroidRuntime: FATAL EXCEPTION: Thread-2
                                                                                         Process: net.opendasharchive.openarchive.release, PID: 15123
                                                                                         java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                                             at android.os.Handler.<init>(Handler.java:200)
                                                                                             at android.os.Handler.<init>(Handler.java:114)
                                                                                             at info.guardianproject.nearby.bluetooth.BluetoothReceiver$2.<init>(BluetoothReceiver.java:206)
                                                                                             at info.guardianproject.nearby.bluetooth.BluetoothReceiver.<init>(BluetoothReceiver.java:205)
                                                                                             at net.opendasharchive.openarchive.nearby.NearbyActivity.startClient(NearbyActivity.java:354)
                                                                                             at net.opendasharchive.openarchive.nearby.NearbyActivity.access$900(NearbyActivity.java:54)
                                                                                             at net.opendasharchive.openarchive.nearby.NearbyActivity$6.run(NearbyActivity.java:262)
12-15 14:52:37.173 4857-7286/? W/ActivityManager:   Force finishing activity net.opendasharchive.openarchive.release/net.opendasharchive.openarchive.nearby.NearbyActivity`

**Comment by n8fr8** [comment]
We've rearchitected the code for nearby share, and don't rely on paired device support anymore.
