### ISSUE TITLE
Error on starting app (Android 8.1.0)

### ISSUE THREAD

**Issue by sabzo** [OpenArchive/Save-app-android#57]
I'm running Open Archive on Android 8.1.0 using a Google Pixel 2 and when starting the app I get the following error:
```
03-04 21:12:52.102 7789-7789/net.opendasharchive.openarchive.release E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: net.opendasharchive.openarchive.release, PID: 7789
                                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{net.opendasharchive.openarchive.release/net.opendasharchive.openarchive.MainActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                        Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class fragment
                                                                                        Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class fragment
                                                                                        Caused by: android.database.sqlite.SQLiteException: no such table: MEDIA (code 1): , while compiling: SELECT * FROM MEDIA ORDER BY ID DESC
                                                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:890)
                                                                                           at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:501)
                                                                                           at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                           at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                           at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                           at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
                                                                                           at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1392)
                                                                                           at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1239)
                                                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1110)
                                                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1316)
                                                                                           at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                                           at com.orm.SugarRecord.listAll(SugarRecord.java:131)
                                                                                           at net.opendasharchive.openarchive.db.Media.getAllMediaAsList(Media.java:282)
                                                                                           at net.opendasharchive.openarchive.fragments.MediaListFragment.initMediaAdapter(MediaListFragment.java:150)
                                                                                           at net.opendasharchive.openarchive.fragments.MediaListFragment.onCreate(MediaListFragment.java:52)
                                                                                           at android.support.v4.app.Fragment.performCreate(Fragment.java:2246)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1377)
                                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1650)
                                                                                           at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1906)
                                                                                           at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:3698)
                                                                                           at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:111)
                                                                                           at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:350)
                                                                                           at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:39)
                                                                                           at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
                                                                                           at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
                                                                                           at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
                                                                                           at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                           at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                           at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
03-04 21:12:52.102 7789-7789/net.opendasharchive.openarchive.release E/AndroidRuntime:     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                           at net.opendasharchive.openarchive.MainActivity.onCreate(MainActivity.java:58)
                                                                                           at android.app.Activity.performCreate(Activity.java:6999)
                                                                                           at android.app.Activity.performCreate(Activity.java:6990)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                           at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

This so far happens on 8.1.0. I tested the app on a Nexus 5 (6.0) and it didn't crash -- I'm thinking this issue is specific only to 8.1.0.

**Comment by sabzo** [comment]
resolved by reinstalling/gradle dependencies.
