### ISSUE TITLE
CRASH OCCUR WHEN ATTEMPTING TO OPEN AN MP3 OT MP4 FILE WITHIN OPRNARCHIVE

### ISSUE THREAD

**Issue by organik1** [OpenArchive/Save-app-android#66]
#### Actual behavior

Openarchive crashes and quits the upload page when attempting to open .mp3 or .mp4 extension files which were imported from sdcard.

#### How to reproduce
* Launch OpenArchive.

* Click on the floating action button, to reveal the import media icon.

* Click the import media icon and import mp4 and mp3extension files from your sdcard.

* After importing, click on any of the files from the home page to access it.

* Then click on the thumbnail within the upload page.

The app should crash and quit the upload page.

#### TESTING ENVIRONMENT

* Browser/App version: v0.0.17 beta 5

* Operating system: Android v6.0 marshmallow

* Device: Itel p12

### Log

```05-27 15:32:20.282 E/AndroidRuntime(17376): FATAL EXCEPTION: main
05-27 15:32:20.282 E/AndroidRuntime(17376): java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/sdcard1/bluetooth/Sia - Freeze You Out.mp3
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at net.opendasharchive.openarchive.ReviewMediaActivity.showMedia(ReviewMediaActivity.java:403)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at net.opendasharchive.openarchive.ReviewMediaActivity.access$100(ReviewMediaActivity.java:55)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at net.opendasharchive.openarchive.ReviewMediaActivity$4.onClick(ReviewMediaActivity.java:366)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at android.view.View.performClick(View.java:4222)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at android.view.View$PerformClick.run(View.java:17628)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at android.os.Handler.handleCallback(Handler.java:800)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at android.os.Looper.loop(Looper.java:194)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at android.app.ActivityThread.main(ActivityThread.java:5370)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at java.lang.reflect.Method.invoke(Method.java:525)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
05-27 15:32:20.282 E/AndroidRuntime(17376): 	at dalvik.system.NativeStart.main(Native Method)`

**Comment by n8fr8** [comment]
We've add "sdcard1" as a valid root.
